### ISSUE TITLE
Criar Rota GET

### ISSUE THREAD

**Issue by Joao-Chagas** [sammytrindade/crud-api#1]
# Service
Dentro de UsersService, será necessário ser criar uma função chamada `read()` que irá listar todos os usuarios (os dados serão mockados no momento atual).
Pode ser visto como exemplo desta função:
```ts
public read() {
  return [
    {
        name: "John Doe",
        age: 15,
    },
    {
        name: "Sammy Doe",
        age: 20,
    }
  ];
}
```

# Controller
Dentro de controller será necessário expor a rota para exibir os usuarios listados no service. Para isso, dentro de UsersController, será necessário criar uma função para exibir os usuarios:
```ts
@Get()
public read() {
   return this.usersService.read();
}
```
Após a criação das funções mostradas acima, será possivel realizar uma requisição para a API e exibir os usuarios.

**Comment by sammytrindade** [comment]
Done.
